services:
  supplier-server:
    container_name: supplier-server
    restart: always
    build: .
    volumes:
      - ./backend:/var/www/localhost/htdocs
    links:
      - supplier-db
    ports:
      - 8250:80
      - 8251:8000
  supplier-db:
    container_name: supplier-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    image: mysql:8.0
    ports:
      - 3350:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: supplier
      MYSQL_PASSWORD: supplier
      MYSQL_DATABASE: supplier
    volumes:
      - ./database:/var/lib/mysql
